name: Daily Create Feature Pipeline

on:
    push:
        branches:
            - main

    schedule:
        - cron: "0 0 * * *" # Run every day at midnight

jobs:
    wine-feature-pipeline-daily:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v2
              with:
                python-version: "3.8"
            - name: Install dependencies
              run:
                python -m pip install --upgrade pip
                pip install pandas hopsworks
            - name: Run script
              run: 
                python lab1/wine/wine-feature-pipeline-daily.py
              env:
                HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

    iris-feature-pipeline-daily:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.8"
            - name: Install dependencies
              run:
                python -m pip install --upgrade pip
                pip install pandas hopsworks seaborn joblib scikit-learn dataframe_image
            - name: Run script
              run: 
                python lab1/iris/iris-feature-pipeline-daily.py
              env:
                HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
            - name: Run inference
              run: 
                python lab1/iris/iris-batch-inference-pipeline.py
